### ISSUE TITLE
Relationship with ide-rust

### ISSUE THREAD

**Issue by keplersj** [AtomLinter/linter-rust#130]
Should this package be deprecated in favor of [`ide-rust`](https://github.com/mehcode/atom-ide-rust)?

cc: @mehcode @gmist @Arcanemagus

**Comment by Arcanemagus** [comment]
It looks like `ide-rust` doesn't run `cargo`, so that's a potential difference. I don't use Rust myself so I don't know if it's important 😛.

_Most_ of the basic `linter-*` providers that have a LSP available for their language are redundant, but in several cases the LSP embeds a different diagnostic provider which means there are still reasons for the individual providers.

The LSP's are also overkill if the user _just_ wants lint messages so I'm not sure I'd say any `ide-*` package really "deprecates" a pure provider like this in my opinion.

**Comment by Arcanemagus** [comment]
Closing based on the above.
