### ISSUE TITLE
linter-rust + Cargo = Error

### ISSUE THREAD

**Issue by azerupi** [AtomLinter/linter-rust#15]
This plug-in produces an error when using Cargo to compile.

See this issue I made in the Cargo repo: https://github.com/rust-lang/cargo/issues/1669

**Comment by colin-kiegel** [comment]
I also get these random concurrency issue.

steps
* atom > packages 'build' + 'linter-rust'
* edit some files
* compile via 'build' package causes simultaneous save of all modified project files 

I suspect tat linter-rust runs cargo *once* per file save, limited by the number of jobs specified in the settings of linter-rust (default: 2). This gives 3 cargo-runs in parallel.

Not good since:
> https://github.com/rust-lang/cargo/issues/354 Concurrent usage of cargo will generally result in badness

1. The best way to solve it, would be upstream cargo - but it's been open for months. Could take long.
2. One could use a different workflow - i.e. don't use 'build' with 'auto-save on build' and set parallel jobs in linter-rust to 1. Then 'save all', wait _sufficiently_ until linter-rust is done, and then 'build'.  Not very nice.
3. So what could we do in atom? Does it make sense for the linter (meta-package) and build to communicate with each other and try to avoid parallel activity? Not so good either.
4. Or could the linter use a shadow-directory structure all-together and let cargo work with something like a duplicate set of temporary files than build? I don't know if that is feasable - but it would be my favourite.

**Comment by colin-kiegel** [comment]
I have written a tiny [**wrapper script**](https://gist.github.com/colin-kiegel/40432d62c70c2ddf7354) for cargo on linux that waits for all previous processes to finish - to avoid the concurrency issues. :-)

This should do the job - until cargo implements its own locking-mechanism.

**Comment by gmist** [comment]
An interesting idea but not cross-platform... I think that [PR712](https://github.com/atom-community/linter/pull/712) will help solve this problem.

**Comment by colin-kiegel** [comment]
You are right, the wrapper is not cross-platform. Still I think it's good to have different approaches until this is fixed in upstream cargo. :-)

**Comment by Arcanemagus** [comment]
@colin-kiegel Your 4. solution above would be relatively simple to implement using the tempFile method from https://github.com/AtomLinter/atom-linter :wink:.

**Comment by azerupi** [comment]
This hasn't happened to me in a while, I think it has been fixed in Cargo? If it has this issue can be closed :)
